#!/usr/bin/env bash

# Azure Cluster Deployment Functions
# Provides Azure-specific cluster deployment utilities with retry logic and failure detection

# Generic cluster deployment with retry logic
# Simplified version without complex failure detection - relies on k0rdent's built-in reconciliation
deploy_cluster_with_retry() {
    local cluster_name="$1"
    local deploy_function="$2"  # Function to call for actual deployment
    local max_retries="${3:-2}"
    local namespace="${4:-kcm-system}"
    local wait_timeout="${5:-1800}"  # 30 minutes default

    local retry_count=0

    print_info "Starting cluster deployment with retry: $cluster_name"
    print_info "Max retries: $max_retries, Wait timeout: ${wait_timeout}s"

    while [[ $retry_count -lt $max_retries ]]; do
        print_header "Deploying cluster $cluster_name (attempt $((retry_count + 1))/$max_retries)"

        # Call the actual deployment function
        if $deploy_function "$cluster_name" "$wait_timeout"; then
            print_success "Cluster deployment succeeded on attempt $((retry_count + 1))"
            return 0
        fi

        ((retry_count++))

        if [[ $retry_count -lt $max_retries ]]; then
            print_warning "Deployment attempt $retry_count failed"
            print_info "Waiting 120s before retry (k0rdent will handle cleanup)..."
            sleep 120
        fi
    done

    print_error "Cluster deployment failed after $max_retries attempts"
    return 1
}

# Validate Azure cluster deployment readiness
validate_azure_cluster_ready() {
    local cluster_name="$1"
    local namespace="${2:-kcm-system}"
    
    print_info "Validating cluster readiness: $cluster_name"
    
    # Check ClusterDeployment status
    local ready_status=$(kubectl get clusterdeployment "$cluster_name" -n "$namespace" \
        -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null)
    
    if [[ "$ready_status" != "True" ]]; then
        print_error "ClusterDeployment Ready status is not True: $ready_status"
        return 1
    fi
    
    # For k0rdent-managed clusters, we cannot reliably determine the resource group name
    # as it's generated by k0rdent. Skip Azure VM validation and rely on k0rdent's Ready status.
    print_info "Note: Azure VM validation skipped for k0rdent-managed cluster"
    print_success "Cluster validation passed based on k0rdent Ready status"
    return 0
}