# k0rdent Development Configuration
# Balanced setup for development teams and testing environments
metadata:
  version: "1.0"
  schema: "k0rdent-config"
  description: "Development environment with moderate resource allocation"

# Azure Infrastructure Settings
azure:
  location: "westus2"
  vm_image: "Debian:debian-12:12-gen2:latest"
  vm_priority: "Regular"

# Network configuration
network:
  vnet_prefix: "10.0.0.0/16"
  subnet_prefix: "10.0.1.0/24"
  wireguard_network: "192.168.100.0/24"

# Moderate VM sizes - balance between cost and capability
vm_sizing:
  controller:
    size: "Standard_B2s"  # 2 vCPU, 4GB RAM - widely available across regions
  worker:
    size: "Standard_B2s"  # 2 vCPU, 4GB RAM - widely available across regions

# Development cluster with some redundancy
cluster:
  controllers:
    count: 1  # Single controller for simplicity
    zones: [2]
  workers:
    count: 2  # Multiple workers for testing distributed workloads
    zones: [2, 3]  # Spread across zones

# SSH Configuration
ssh:
  username: "k0rdent"
  key_comment: "k0rdent-azure-key"

# Software Versions
software:
  k0s:
    version: "v1.33.1+k0s.0"
  k0rdent:
    version: "1.0.0"
    registry: "oci://ghcr.io/k0rdent/kcm/charts/kcm"
    namespace: "kcm-system"

# Standard timeouts suitable for development
timeouts:
  ssh_connect: 30
  k0s_install_wait: 90
  k0rdent_install_wait: 1500
  wireguard_connect_wait: 5
  vm_creation_minutes: 15
  vm_wait_check_interval: 30
  verification_retries: 3
  verification_retry_delay: 10

# KOF Configuration - Example showing how to enable KOF
# Uncomment and modify as needed for development environments
# kof:
#   enabled: true  # Enable KOF for this deployment
#   version: "1.1.0"