# k0rdent Minimal Configuration
# Single controller+worker node for development and testing
metadata:
  version: "1.0"
  schema: "k0rdent-config"
  description: "Minimal single-node development setup"

# Azure Infrastructure Settings
azure:
  location: "westus2"
  vm_image: "Debian:debian-12:12-gen2:latest"
  vm_priority: "Regular"

# Network configuration
network:
  vnet_prefix: "10.0.0.0/16"
  subnet_prefix: "10.0.1.0/24"
  wireguard_network: "192.168.100.0/24"

# Use smaller VM sizes for cost savings
vm_sizing:
  controller:
    size: "Standard_B2s"  # 2 vCPU, 4GB RAM - widely available across regions
  worker:
    size: "Standard_B2s"  # Same size for simplicity

# Single node cluster
cluster:
  controllers:
    count: 1
    zones: [1]  # Single zone
  workers:
    count: 1
    zones: [1]  # Single zone

# SSH Configuration
ssh:
  username: "k0rdent"
  key_comment: "k0rdent-azure-key"

# Software Versions
software:
  k0s:
    version: "v1.33.1+k0s.0"
  k0rdent:
    version: "1.0.0"
    registry: "oci://ghcr.io/k0rdent/kcm/charts/kcm"
    namespace: "kcm-system"

# Reduced timeouts for faster development cycles
timeouts:
  ssh_connect: 30
  k0s_install_wait: 30
  k0rdent_install_wait: 1500
  wireguard_connect_wait: 5
  vm_creation_minutes: 10
  vm_wait_check_interval: 30
  verification_retries: 3
  verification_retry_delay: 10